### ISSUE TITLE
trader command not added 

### ISSUE THREAD

**Issue by shehzaad777** [CSC207-UofT/course-project-stress_coders#64]
the command that allows trading is not yet don't, could be added to talk_to with the right modifications or maybe create a new command choice is yours but get it done and send an @ to Shehzaad when done on discord to populate builder with it

**Comment by devan-srinivasan** [comment]
on it!

**Comment by devan-srinivasan** [comment]
Fixed it with PR #80 Close when satisfied shehzaad

**Comment by shehzaad777** [comment]
all good, just waiting on howToUse to close
