### ISSUE TITLE
Completion of an Encounter

### ISSUE THREAD

**Issue by devan-srinivasan** [CSC207-UofT/course-project-stress_coders#8]
We need to have an arbitrary way of knowing when an Encounter is completed. Conrad discussed an interesting solution where every interactable has a `bool completed;` attribute. If this attribute is set to True by default it is auto-completed (nothing **needs** to be done with it, although you can interact with it). If this attribute is set to False then something within the gameobject (for example an enemy dying) will set this attribute to True. This way, an encounter will be "completed" when all interactables within it are completed, and this can be easily validated in the game state. It is a clean solution. will await review from the rest of the group.

**Comment by HenriLD** [comment]
implemented a check that's false by default, will implement an option to make it always true
