### ISSUE TITLE
SpinCommand in interfaceadapters 

### ISSUE THREAD

**Issue by riyanah** [CSC207-UofT/course-project-stress_coders#93]
Shouldn't there be a SpinCommand in interfaceadapters @MichelleChernyi  
I can make it if you want

**Comment by devan-srinivasan** [comment]
hey @riyanah i went ahead and fixed it since it was apart of the work Michelle and I were doing. Thanks for the observation!
#95

**Comment by devan-srinivasan** [comment]
Once you merge my PR (assuming its all good) you can close this issue.
